CREATE TABLE IF NOT EXISTS `exceptions_` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `bot_guid` varchar(80) NOT NULL,
  `bot_version` int(5) unsigned NOT NULL,
  `system_proc_arch` int(5) unsigned default NULL,
  `system_dep` tinyint(1) default NULL,
  `system_pae` tinyint(1) default NULL,
  `system_proc_cnt` int(5) unsigned default NULL,
  `os_version` varchar(20) default NULL,
  `os_sp_version` varchar(142) default NULL,
  `os_suite_mask` int(5) unsigned default NULL,
  `os_product_type` int(5) unsigned default NULL,
  `os_x64` tinyint(1) default NULL,
  `app_path` varchar(160) default NULL,
  `app_cname` varchar(256) character set ucs2 collate ucs2_bin default NULL,
  `app_pname` varchar(256) character set ucs2 collate ucs2_bin default NULL,
  `app_pver` varchar(256) default NULL,
  `app_fver` varchar(256) default NULL,
  `user_type` int(1) unsigned NOT NULL,
  `ex_code` int(10) unsigned NOT NULL,
  `ex_method` int(10) unsigned NOT NULL,
  `ex_pid` int(10) unsigned NOT NULL,
  `ex_addr` int(10) unsigned NOT NULL,
  `ex_reqaddr` int(10) unsigned NOT NULL,
  `ex_aseh` int(10) unsigned NOT NULL,
  `reg_eax` int(10) unsigned NOT NULL,
  `reg_ecx` int(10) unsigned NOT NULL,
  `reg_edx` int(10) unsigned NOT NULL,
  `reg_ebx` int(10) unsigned NOT NULL,
  `reg_esi` int(10) unsigned NOT NULL,
  `reg_edi` int(10) unsigned NOT NULL,
  `reg_ebp` int(10) unsigned NOT NULL,
  `reg_esp` int(10) unsigned NOT NULL,
  `ticks` int(10) unsigned NOT NULL,
  `stack_0` int(10) unsigned NOT NULL,
  `stack_0_desc` varchar(260) default NULL,
  `stack_1` int(10) unsigned NOT NULL,
  `stack_1_desc` varchar(260) default NULL,
  `stack_2` int(10) unsigned NOT NULL,
  `stack_2_desc` varchar(260) default NULL,
  `stack_3` int(10) unsigned NOT NULL,
  `stack_3_desc` varchar(260) default NULL,
  `stack_4` int(10) unsigned NOT NULL,
  `stack_4_desc` varchar(260) default NULL,
  `stack_5` int(10) unsigned NOT NULL,
  `stack_5_desc` varchar(260) default NULL,
  `stack_6` int(10) unsigned NOT NULL,
  `stack_6_desc` varchar(260) default NULL,
  `stack_7` int(10) unsigned NOT NULL,
  `stack_7_desc` varchar(260) default NULL,
  `stack_8` int(10) unsigned NOT NULL,
  `stack_8_desc` varchar(260) default NULL,
  `stack_9` int(10) unsigned NOT NULL,
  `stack_9_desc` varchar(260) default NULL,
  `stack_10` int(10) unsigned NOT NULL,
  `stack_10_desc` varchar(260) default NULL,
  `stack_11` int(10) unsigned NOT NULL,
  `stack_11_desc` varchar(260) default NULL,
  `stack_12` int(10) unsigned NOT NULL,
  `stack_12_desc` varchar(260) default NULL,
  `stack_13` int(10) unsigned NOT NULL,
  `stack_13_desc` varchar(260) default NULL,
  `stack_14` int(10) unsigned NOT NULL,
  `stack_14_desc` varchar(260) default NULL,
  `stack_15` int(10) unsigned NOT NULL,
  `stack_15_desc` varchar(260) default NULL,
  `stack_16` int(10) unsigned NOT NULL,
  `stack_16_desc` varchar(260) default NULL,
  `stack_17` int(10) unsigned NOT NULL,
  `stack_17_desc` varchar(260) default NULL,
  `stack_18` int(10) unsigned NOT NULL,
  `stack_18_desc` varchar(260) default NULL,
  `stack_19` int(10) unsigned NOT NULL,
  `stack_19_desc` varchar(260) default NULL,
  `bot_base_addr` int(10) unsigned NOT NULL,
  `cmodule_name` varchar(260) default NULL,
  `disasm` varchar(10000) default NULL,
  `date_rep` datetime NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
