<?php

$lang["ru"] = array
(
	"Статистика",
	"Задачи",
	"Управление",
	"Панель управления",
	"Ошибка загрузки файла!",
	"кб",
	"Удалить",
	"Править",
	"Пауза",
	"Старт",
	"Пока данных нет...",
	"Управление файлами",
	"Обновить геотаргетинг",
	"закрыть",
	"Обновить",
	"Пример",
	"Обновить внешний файл",
	"Обновить файл",
	"Добавить",
	"Файл",
	"Загрузка",
	"Локальный",
	"Удаленный",
	"Из списка",
	"Вручную",
	"Размер",
	"Лимит",
	"Запусков",
	"Действия",
	"Действия с БД",
	"Описание",
	"Действие",
	"Удалить все задания",
	"Удалить всю статистику",
	"Оптимизация БД",
	"Анализ БД",
	"График",
	"Описание",
	"Счетчик",
	"Всего ботов",
	"Заданий",
	"Всего загрузок",
	"Всего запусков",
	"Последние 5 ботов",
	"Страна",
	"Дата",
	"Статистика по системам",
	"Система",
	"Ботов",
	"Статистика по странам",
	"Состав модулей",
	"Модуль",
	"Состояние",
	"Включен",
	"Отключен",
	"Файл удален!",
	"Файл не выбран!",
	"!Слишком много задачь!",
	"!Файл не найден!",
	"!Путь не выбран!",
	"Вы вошли как",
	"Ботов онлайн",
	"Ботов оффлайн"
);

$lang["en"] = array
(
	"Statistics",
	"Tasks",
	"Manage",
	"Control panel",
	"Error uploading file!",
	"kb",
	"Delete",
	"Edit",
	"Pause",
	"Start",
	"No stats aviable",
	"Files operations",
	"Update geo",
	"close",
	"Update",
	"Example",
	"Update external file",
	"Update file",
	"Upload",
	"File",
	"Loading",
	"Local",
	"Remote",
	"From list",
	"Manual",
	"Size",
	"Limits",
	"Executes",
	"Actions",
	"DB actions",
	"Description",
	"Action",
	"Kill all tasks",
	"Clear stats",
	"DB optimize",
	"DB analyseing",
	"Graph",
	"Description",
	"Count",
	"Total bots",
	"Tasks",
	"Downloads",
	"Total executes",
	"Last 5 bots",
	"Country",
	"Date",
	"OS stats",
	"OS",
	"Bots",
	"Country stats",
	"Modules",
	"Module",
	"Activity",
	"On",
	"Off",
	"File deleted",
	"Select file first!",
	"!Too many tasks!",
	"!File not found!",
	"!Path not found!",
	"You are logged in as",
	"Online",
	"Offline"
);

?>